directory: "//NDATA9/daviss1$/My Documents/QIP work/Completed QIPs"

null_values:
  - NA
  - "-"
  - "- "
  - "NA"
  - "NA "
  - "N/A"
  - "N/A "
  - "na"
  - "na "
  - "n/a"
  - "n/a "
  - "N/a"
  - "N/a "
  - "none"
  - "None"
  - "NONE"
  - "none "
  - "None "
  - "NONE "

metric_ranges:
  - "B4:P8"
  - "B10:P14"
  - "B17:P21"
  - "B24:P28"

reporting_months:
  this_month: "November 2021"
  previous_month: NA
